language: java
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
  sonarcloud: true
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
# prevents ./gradlew assemble from running
install: true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.sonar"
script:
  - "./gradlew build"
deploy:
  provider: heroku
  api_key:
    secure: QahG7hlJi0s3p5s9z0YhwLoe4lRfLM+ESoBhem5NWcOTQwL9U7Qai4EFklOVGL2P2nPCtupsJpYg+lw+EJrbP3QN1FBtQmCnMwqAjHXZLUy0m33EcpYnhKODfv+g9/MIU/sHTvzoqtUfGTdm6zp7Ize6IfDe8T5M2MSasVD4tU0PXk5nJFr3q9ixxja4VLzBqIocNBVCAKZBxKCmhpQBlIMYffxMh+XK9bfoAXvR7Bzp84OcVlIj5odIRWTea926WDiqgn8WXYUGlTGvjt9IBMovfUfaAU6D7MxhuILgt++KuIMf9Yuv0g25Mhb+FNAIXpO/w75XxVzDZwL7KXTjnwp0GD5KGsYqz720RIIMRv8EeTdby9ujb+nex5WF1j2F/m/gWq6GerP/6vUtogvaeZ1/bsh3VSATB9VVsn+SUJvj1KXaDJGkbm4BvkoV579gEvbzUs+hK0+YF1OPyI7YJ8lX0EnCAjo7Vox9/FPRqhfg2SmQ35+qggqhiCXsiXbAkhzIo7cXvE9uTXZmI1WD3NYV2CDgxiXE0NicTgUVZHeXwIkrIJSinyE68kHYhbQ/F/g57KgpqviEWP7BDGnsvCMKIfVzX6Hjix5isqvjyF+JYa2lKyqWfmiGIQ6jaNRXvUwc+fVFko415lyymf44Z3SSK4J/cUD+ZnnXcnqtGLg=
  app:
    develop: gloat-develop
    master: gloat
  on:
    repo: vandiedakaf/gloat
branches:
  only:
  - master
  - release
  - develop
after_success:
  - "./gradlew jacocoTestReport coveralls"
  - "sonar-scanner -Dsonar.login=$SONAR_TOKEN"
notifications:
  email: false
env:
  global:
    - secure: "dL6de0yw+A7q4pDurv2D+O/QtfGe7qc6FB0SzcMZzL2xz1mvAZUiBnt2tMfhm5wXAijus2afshFlpo+/AUwlAPq0TFj9bssSR+Xuz8k7MybedJG7s7VHfbcRcgJMedg+hkDxrsKXFD4tle64nbKQyQD4vNlIbXy/m2qabKawUBMyGQJnjInZJ5SQk3db3qoFmhcmJ02aUwHQ6RLkv8rTt4ZKkfRAeJmp1FZ1UsLlbEg3ADtPMM5xN67lCY
      fSstvM6ls+FvNGyjYmqr4ZU8y3dU548+TiVEZkky5x35Eq2MxQLM5/zPSgeTgU5GIdHH/880aEG86gbiRJKJFGyadIHJdQzu4PLpePgC3xzG5KxNkE6NHNyLfJOw9oDSeERbyt48vPYq0GcJhFbjcz5AcorX/MSovLbUeJencYwNhZvCOR3n5KHbgzH5T7TXMYKcF6KC/MYnPu49wV05hjTkvjxjLbCWbY0WHMu6FfOLCH+UeaqM6oC0Vytz/ho01BCWT
      HEw75Xc/a9+ugbOW/1fFYZz9vAN4SmYzO9R5fcg91cwXpStQMN0AfzpFdszbs0kqdMIkI8MzN9KWLHlXv38Bt4EvQ+WIqgHTnQiy5R+tMnYdIPt0OFw82V3Wz0eoofpd/SHzPHjzsjnUp4NL1rXYVs046vRjS3HluJrjycspTNbI="
