language: java
services: mysql
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
install: true # prevents ./gradlew assemble from running
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
  - "mysql -uroot --execute=""CREATE DATABASE `gloat`"""
  - "./gradlew build"
branches:
  only:
  - master
  - develop
after_success:
 - ./gradlew jacocoTestReport coveralls
notifications:
  email: false
