language: java
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.7
    - mysql-client-core-5.7
    - mysql-client-5.7
  sonarqube: true
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - chmod +x gradlew
  - chmod +x deploy-staging.sh
  - chmod +x deploy-production.sh
# prevents ./gradlew assemble from running
install: true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.sonar"
  - "$HOME/google-cloud-sdk/"
script:
  - "./gradlew build -x test"
before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl
deploy:
  - provider: script
    script: ./deploy-staging.sh
    skip_cleanup: true
    on:
      branch: development
  - provider: script
    script: ./deploy-staging.sh
    skip_cleanup: true
    on:
      branch: master
branches:
  only:
  - master
  - release
  - develop
after_success:
#  - "./gradlew jacocoTestReport coveralls"
#  - "sonar-scanner -Dsonar.login=$SONAR_TOKEN"
notifications:
  email: false
env:
  global:
    - secure: "dL6de0yw+A7q4pDurv2D+O/QtfGe7qc6FB0SzcMZzL2xz1mvAZUiBnt2tMfhm5wXAijus2afshFlpo+/AUwlAPq0TFj9bssSR+Xuz8k7MybedJG7s7VHfbcRcgJMedg+hkDxrsKXFD4tle64nbKQyQD4vNlIbXy/m2qabKawUBMyGQJnjInZJ5SQk3db3qoFmhcmJ02aUwHQ6RLkv8rTt4ZKkfRAeJmp1FZ1UsLlbEg3ADtPMM5xN67lCY
      fSstvM6ls+FvNGyjYmqr4ZU8y3dU548+TiVEZkky5x35Eq2MxQLM5/zPSgeTgU5GIdHH/880aEG86gbiRJKJFGyadIHJdQzu4PLpePgC3xzG5KxNkE6NHNyLfJOw9oDSeERbyt48vPYq0GcJhFbjcz5AcorX/MSovLbUeJencYwNhZvCOR3n5KHbgzH5T7TXMYKcF6KC/MYnPu49wV05hjTkvjxjLbCWbY0WHMu6FfOLCH+UeaqM6oC0Vytz/ho01BCWT
      HEw75Xc/a9+ugbOW/1fFYZz9vAN4SmYzO9R5fcg91cwXpStQMN0AfzpFdszbs0kqdMIkI8MzN9KWLHlXv38Bt4EvQ+WIqgHTnQiy5R+tMnYdIPt0OFw82V3Wz0eoofpd/SHzPHjzsjnUp4NL1rXYVs046vRjS3HluJrjycspTNbI="
