#
# vandiedakaf solutions 2016
#
logging:
  level:
    org.springframework.web: INFO
    com.vdda: DEBUG
    org.meanbean: INFO

spring:
  datasource: # these credentials are typically replaced with environment variables
    url: jdbc:mysql://localhost/gloat?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: none # https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html#boot-features-creating-and-dropping-jpa-databases
  output:
    ansi:
      enabled: always

management:
#  port: 9000
  security:
   enabled: true

security:
  basic:
    authorize-mode: none

env:
  elo-init: 1500

---
spring:
  profiles: local
  datasource:
      password: password

logging:
  level:
    org.springframework.web: INFO
    com.vdda: DEBUG