env.elo-init: 1500

logging:
  level:
    org.springframework.web: INFO
    com.vdda: DEBUG

management.security.enabled: true

security.basic.authorize-mode: none

spring:
  application.name: gloat
  datasource.driver-class-name: com.mysql.jdbc.Driver
  jpa.hibernate.ddl-auto: none # https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html#boot-features-creating-and-dropping-jpa-databases
  output.ansi.enabled: detect
  sleuth.sampler.percentage: 0.1
