#
# vandiedakaf solutions 2016
#

logging:
  level:
    org.springframework.web: INFO
    com.vdda: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost/gloat?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: none # https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html#boot-features-creating-and-dropping-jpa-databases

management:
  port: 9000
  security:
   enabled: true

security:
  basic:
    authorize-mode: none
