logging:
  level:
    org.springframework.web: INFO
    com.vdda: DEBUG

spring:
  datasource: # these credentials are typically replaced with environment variables
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: none # https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html#boot-features-creating-and-dropping-jpa-databases
  output:
    ansi:
      enabled: detect

management:
  security:
   enabled: true

security:
  basic:
    authorize-mode: none

env:
  elo-init: 1500